<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ALDPC0692" name="com.fanbei.login" tests="11" failures="8" timestamp="12 Sep 2017 06:54:58 GMT" time="1.151" errors="0">
  <testcase name="UserLogin" time="0.707" classname="com.fanbei.login.UserLoginTest"/>
  <testcase name="UserLogin" time="0.037" classname="com.fanbei.login.UserLoginTest">
    <failure type="java.lang.AssertionError" message="expected [1005] but found [1015]">
      <![CDATA[java.lang.AssertionError: expected [1005] but found [1015]
	at com.fanbei.login.UserLoginTest.UserLogin(UserLoginTest.java:88)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- UserLogin -->
  <testcase name="UserLogin" time="0.029" classname="com.fanbei.login.UserLoginTest">
    <failure type="java.lang.AssertionError" message="expected [1005] but found [1015]">
      <![CDATA[java.lang.AssertionError: expected [1005] but found [1015]
	at com.fanbei.login.UserLoginTest.UserLogin(UserLoginTest.java:88)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- UserLogin -->
  <testcase name="UserLogin" time="0.032" classname="com.fanbei.login.UserLoginTest">
    <failure type="java.lang.AssertionError" message="expected [1005] but found [1015]">
      <![CDATA[java.lang.AssertionError: expected [1005] but found [1015]
	at com.fanbei.login.UserLoginTest.UserLogin(UserLoginTest.java:88)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- UserLogin -->
  <testcase name="UserLogin" time="0.032" classname="com.fanbei.login.UserLoginTest">
    <failure type="java.lang.AssertionError" message="expected [1005] but found [1015]">
      <![CDATA[java.lang.AssertionError: expected [1005] but found [1015]
	at com.fanbei.login.UserLoginTest.UserLogin(UserLoginTest.java:88)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- UserLogin -->
  <testcase name="GetUserInfo" time="0.056" classname="com.fanbei.login.GetUserInfoTest"/>
  <testcase name="GetUserInfo" time="0.027" classname="com.fanbei.login.GetUserInfoTest">
    <failure type="java.lang.AssertionError" message="expected [1005] but found [1015]">
      <![CDATA[java.lang.AssertionError: expected [1005] but found [1015]
	at com.fanbei.login.GetUserInfoTest.GetUserInfo(GetUserInfoTest.java:54)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- GetUserInfo -->
  <testcase name="GetUserInfo" time="0.024" classname="com.fanbei.login.GetUserInfoTest">
    <failure type="java.lang.AssertionError" message="expected [1005] but found [1015]">
      <![CDATA[java.lang.AssertionError: expected [1005] but found [1015]
	at com.fanbei.login.GetUserInfoTest.GetUserInfo(GetUserInfoTest.java:54)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- GetUserInfo -->
  <testcase name="UserGetMineInfo" time="0.116" classname="com.fanbei.login.UserGetMineInfoTest"/>
  <testcase name="UserGetMineInfo" time="0.033" classname="com.fanbei.login.UserGetMineInfoTest">
    <failure type="java.lang.AssertionError" message="expected [1005] but found [1015]">
      <![CDATA[java.lang.AssertionError: expected [1005] but found [1015]
	at com.fanbei.login.UserGetMineInfoTest.UserGetMineInfo(UserGetMineInfoTest.java:54)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- UserGetMineInfo -->
  <testcase name="UserGetMineInfo" time="0.024" classname="com.fanbei.login.UserGetMineInfoTest">
    <failure type="java.lang.AssertionError" message="expected [1005] but found [1015]">
      <![CDATA[java.lang.AssertionError: expected [1005] but found [1015]
	at com.fanbei.login.UserGetMineInfoTest.UserGetMineInfo(UserGetMineInfoTest.java:54)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- UserGetMineInfo -->
</testsuite> <!-- com.fanbei.login -->
